swagger: "2.0"
info:
  description: Fichier swagger associé à notre API
  version: "1.0.0"
  title: Swagger pour API ReST
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /users:
    post:
      operationId: user.create
      tags:
        - Users
      summary: Enregistrer une personne dans la liste user
      description: Créer un nouvel enregistrement user
      parameters:
        - name: user
          in: body
          description: Enregistrement à créer
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: Nom de la personne
              competences:
                type: string
                description: Compétences de la personne
              age:
                type: integer
                description: Age de la personne
              cv:
                type: string
                description: CV de la personne
      responses:
        201:
          description: Succès dans la création
    
    get:
      operationId: user.read_all
      tags:
        - Users
      summary: Lecture de la liste entière
      description: Lire la liste de personnes
      parameters:
        - name: length
          in: query
          type: integer
          description: Nombre de personnes dont on récupère les données dans user
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset de début de liste où lire les données
          required: false
      responses:
        200:
          description: Succès dans la lecture
          schema:
            type: array
            items:
              type: object
              properties:
                username:
                  type: string
                  description: Nom de la personne
                competences:
                  type: string
                  description: Compétences de la personne
                age:
                  type: integer
                  description: Age de la personne
                cv:
                  type: string
                  description: CV de la personne


  /users/{id}:
      get:
        operationId: user.read_one
        tags:
          - Users
        summary: Lire les données d'une personne dans la liste user
        description: Lire un enregistrement dans la liste user
        parameters:
          - name: id
            in: path
            description: ID de la personne
            type: integer
            required: true
        responses:
          200:
            description: Succès dans la lecture
            schema:
              properties:
                username:
                  type: string
                  description: Nom de la personne
                competences:
                  type: string
                  description: Compétences de la personne
                age:
                  type: integer
                  description: Age de la personne
                cv:
                  type: string
                  description: CV de la personne
      put:
        operationId: user.update
        tags:
          - Users
        summary: Mettre à jour les données d'une personne dans la liste user
        description: Mettre à jour un enregistrement
        parameters:
          - name: id
            in: path
            description: ID de la personne
            type: integer
            required: true
          - name: user_data
            in: body
            description: Enregistrement à mettre à jour
            required: true
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Nom de la personne
                competences:
                  type: string
                  description: Compétences de la personne
                age:
                  type: integer
                  description: Age de la personne
                cv:
                  type: string
                  description: CV de la personne
        responses:
          200:
            description: Succès dans la mise à jour
          404:
            description: Utilisateur non trouvé
